version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11030871aqz
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: E:/Програмирование. Учеба/Ping/SpringPing/back-end
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ping
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 11030871aqz

  frontend:
    build:
      context: E:/Програмирование. Учеба/Ping/SpringPing/front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

